import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Skolträning",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap" rel="stylesheet" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        <footer>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320" preserveAspectRatio="none">
            <path fill="#0099ff" d="M0,64L26.7,74.7C53.3,85,107,107,160,144C213.3,181,267,235,320,229.3C373.3,224,427,160,480,154.7C533.3,149,587,203,640,218.7C693.3,235,747,213,800,202.7C853.3,192,907,192,960,181.3C1013.3,171,1067,149,1120,154.7C1173.3,160,1227,192,1280,176C1333.3,160,1387,96,1413,64L1440,32L1440,320L1413.3,320C1386.7,320,1333,320,1280,320C1226.7,320,1173,320,1120,320C1066.7,320,1013,320,960,320C906.7,320,853,320,800,320C746.7,320,693,320,640,320C586.7,320,533,320,480,320C426.7,320,373,320,320,320C266.7,320,213,320,160,320C106.7,320,53,320,27,320L0,320Z"></path>
          </svg>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320" preserveAspectRatio="none">
            <path fill="#0099ff" d="M0,192L20,208C40,224,80,256,120,224C160,192,200,96,240,74.7C280,53,320,107,360,112C400,117,440,75,480,58.7C520,43,560,53,600,101.3C640,149,680,235,720,272C760,309,800,299,840,261.3C880,224,920,160,960,117.3C1000,75,1040,53,1080,48C1120,43,1160,53,1200,101.3C1240,149,1280,235,1320,266.7C1360,299,1400,277,1420,266.7L1440,256L1440,320L1420,320C1400,320,1360,320,1320,320C1280,320,1240,320,1200,320C1160,320,1120,320,1080,320C1040,320,1000,320,960,320C920,320,880,320,840,320C800,320,760,320,720,320C680,320,640,320,600,320C560,320,520,320,480,320C440,320,400,320,360,320C320,320,280,320,240,320C200,320,160,320,120,320C80,320,40,320,20,320L0,320Z"></path>
          </svg>
          <div></div>
          <div></div>
        </footer>
      </body>
    </html>
  );
}
